spring.application.name=demo

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gdananyapt@gmail.com
spring.mail.password=mlcqfpwuthhhqfvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true